using UnityEditor;
using UnityEditor.UI;
using UnityEngine;
using UnityEngine.UI;

namespace ProjectArea.UI.Editor
{
    [CustomEditor(typeof(FigmaImage), true)]
    [CanEditMultipleObjects]
    public class FigmaImageEditor : ImageEditor
    {
        private SerializedProperty m_CornerRadiusProp;
        private SerializedProperty m_LinkCorners;
        private SerializedProperty m_Radius;
        private SerializedProperty m_CornerRadii;

        private SerializedProperty m_StrokeProp;
        private SerializedProperty m_StrokeEnabled;
        private SerializedProperty m_StrokeWidth;
        private SerializedProperty m_StrokeColor;
        private SerializedProperty m_StrokePosition;
        private SerializedProperty m_StrokeIgnoreInMask;

        private SerializedProperty m_DropShadowProp;
        private SerializedProperty m_ShadowEnabled;
        private SerializedProperty m_ShadowOffsetX;
        private SerializedProperty m_ShadowOffsetY;
        private SerializedProperty m_ShadowBlur;
        private SerializedProperty m_ShadowSpread;
        private SerializedProperty m_ShadowColor;

        private SerializedProperty m_InnerShadowProp;
        private SerializedProperty m_InnerShadowEnabled;
        private SerializedProperty m_InnerShadowOffsetX;
        private SerializedProperty m_InnerShadowOffsetY;
        private SerializedProperty m_InnerShadowBlur;
        private SerializedProperty m_InnerShadowSpread;
        private SerializedProperty m_InnerShadowColor;

        private SerializedProperty m_UseRoundedRaycast;

        private readonly GUIContent m_CornerRadiusHeader = new GUIContent("Corner Radius", "Figma-style corner radius controls in pixels.");
        private readonly GUIContent m_LinkCornersContent = new GUIContent("Link Corners", "When enabled, all four corners share the same radius.");
        private readonly GUIContent m_RadiusContent = new GUIContent("Radius", "Pixel radius applied to all corners.");
        private readonly GUIContent m_TopLeftContent = new GUIContent("Top Left", "Pixel radius for top-left corner.");
        private readonly GUIContent m_TopRightContent = new GUIContent("Top Right", "Pixel radius for top-right corner.");
        private readonly GUIContent m_BottomRightContent = new GUIContent("Bottom Right", "Pixel radius for bottom-right corner.");
        private readonly GUIContent m_BottomLeftContent = new GUIContent("Bottom Left", "Pixel radius for bottom-left corner.");

        private readonly GUIContent m_StrokeHeader = new GUIContent("Stroke", "Figma-style inside stroke controls.");
        private readonly GUIContent m_StrokeEnabledContent = new GUIContent("Enabled", "Enable inside stroke rendering.");
        private readonly GUIContent m_StrokeWidthContent = new GUIContent("Width", "Stroke width in pixels.");
        private readonly GUIContent m_StrokeColorContent = new GUIContent("Color", "Stroke color.");
        private readonly GUIContent m_StrokePositionContent = new GUIContent("Position", "Stroke alignment position.");
        private readonly GUIContent m_StrokeIgnoreInMaskContent = new GUIContent("Ignore In Mask", "When enabled, clipping masks generated by this graphic will clip child content strictly inside the stroke, keeping the outline visible.");

        private readonly GUIContent m_EffectsHeader = new GUIContent("Effects", "Visual effects controls.");
        private readonly GUIContent m_DropShadowHeader = new GUIContent("Drop Shadow", "Figma-style drop shadow controls.");
        private readonly GUIContent m_ShadowEnabledContent = new GUIContent("Enabled", "Enable drop shadow rendering.");
        private readonly GUIContent m_ShadowXContent = new GUIContent("X", "Horizontal offset in pixels. Positive moves right.");
        private readonly GUIContent m_ShadowYContent = new GUIContent("Y", "Vertical offset in pixels. Positive moves down (Figma convention).");
        private readonly GUIContent m_ShadowBlurContent = new GUIContent("Blur", "Shadow blur radius in pixels.");
        private readonly GUIContent m_ShadowSpreadContent = new GUIContent("Spread", "Shadow spread distance in pixels.");
        private readonly GUIContent m_ShadowColorContent = new GUIContent("Color", "Shadow RGBA color.");

        private readonly GUIContent m_InnerShadowHeader = new GUIContent("Inner Shadow", "Figma-style inner shadow controls.");
        private readonly GUIContent m_InnerShadowEnabledContent = new GUIContent("Enabled", "Enable inner shadow rendering.");
        private readonly GUIContent m_InnerShadowXContent = new GUIContent("X", "Horizontal offset in pixels. Positive moves right.");
        private readonly GUIContent m_InnerShadowYContent = new GUIContent("Y", "Vertical offset in pixels. Positive moves down (Figma convention).");
        private readonly GUIContent m_InnerShadowBlurContent = new GUIContent("Blur", "Inner shadow blur radius in pixels.");
        private readonly GUIContent m_InnerShadowSpreadContent = new GUIContent("Spread", "Inner shadow spread distance in pixels. Positive pushes shadow inward.");
        private readonly GUIContent m_InnerShadowColorContent = new GUIContent("Color", "Inner shadow RGBA color.");

        private readonly GUIContent m_RaycastContent = new GUIContent("Rounded Raycast", "Reject raycasts outside the rounded shape.");

        protected override void OnEnable()
        {
            base.OnEnable();

            m_CornerRadiusProp = serializedObject.FindProperty("m_CornerRadius");
            if (m_CornerRadiusProp != null)
            {
                m_LinkCorners = m_CornerRadiusProp.FindPropertyRelative("m_LinkCorners");
                m_Radius = m_CornerRadiusProp.FindPropertyRelative("m_Radius");
                m_CornerRadii = m_CornerRadiusProp.FindPropertyRelative("m_CornerRadii");
            }

            m_StrokeProp = serializedObject.FindProperty("m_Stroke");
            if (m_StrokeProp != null)
            {
                m_StrokeEnabled = m_StrokeProp.FindPropertyRelative("m_Enabled");
                m_StrokeWidth = m_StrokeProp.FindPropertyRelative("m_Width");
                m_StrokeColor = m_StrokeProp.FindPropertyRelative("m_Color");
                m_StrokePosition = m_StrokeProp.FindPropertyRelative("m_Position");
                m_StrokeIgnoreInMask = m_StrokeProp.FindPropertyRelative("m_IgnoreInMask");
            }

            m_DropShadowProp = serializedObject.FindProperty("m_DropShadow");
            if (m_DropShadowProp != null)
            {
                m_ShadowEnabled = m_DropShadowProp.FindPropertyRelative("m_Enabled");
                m_ShadowOffsetX = m_DropShadowProp.FindPropertyRelative("m_OffsetX");
                m_ShadowOffsetY = m_DropShadowProp.FindPropertyRelative("m_OffsetY");
                m_ShadowBlur = m_DropShadowProp.FindPropertyRelative("m_Blur");
                m_ShadowSpread = m_DropShadowProp.FindPropertyRelative("m_Spread");
                m_ShadowColor = m_DropShadowProp.FindPropertyRelative("m_Color");
            }

            m_InnerShadowProp = serializedObject.FindProperty("m_InnerShadow");
            if (m_InnerShadowProp != null)
            {
                m_InnerShadowEnabled = m_InnerShadowProp.FindPropertyRelative("m_Enabled");
                m_InnerShadowOffsetX = m_InnerShadowProp.FindPropertyRelative("m_OffsetX");
                m_InnerShadowOffsetY = m_InnerShadowProp.FindPropertyRelative("m_OffsetY");
                m_InnerShadowBlur = m_InnerShadowProp.FindPropertyRelative("m_Blur");
                m_InnerShadowSpread = m_InnerShadowProp.FindPropertyRelative("m_Spread");
                m_InnerShadowColor = m_InnerShadowProp.FindPropertyRelative("m_Color");
            }

            m_UseRoundedRaycast = serializedObject.FindProperty("m_UseRoundedRaycast");
        }

        public override void OnInspectorGUI()
        {
            // Standard Image inspector fields
            base.OnInspectorGUI();

            serializedObject.Update();

            // ── Corner Radius Section ──
            EditorGUILayout.Space(6);
            EditorGUILayout.LabelField(m_CornerRadiusHeader, EditorStyles.boldLabel);

            if (m_LinkCorners != null && m_Radius != null && m_CornerRadii != null)
            {
                EditorGUI.BeginChangeCheck();
                EditorGUILayout.PropertyField(m_LinkCorners, m_LinkCornersContent);

                if (m_LinkCorners.boolValue)
                {
                    EditorGUI.BeginChangeCheck();
                    float newRadius = EditorGUILayout.FloatField(m_RadiusContent, m_Radius.floatValue);
                    if (EditorGUI.EndChangeCheck())
                    {
                        newRadius = Mathf.Max(0f, newRadius);
                        m_Radius.floatValue = newRadius;
                        m_CornerRadii.vector4Value = new Vector4(newRadius, newRadius, newRadius, newRadius);
                    }
                }
                else
                {
                    Vector4 current = m_CornerRadii.vector4Value;

                    EditorGUI.indentLevel++;
                    EditorGUI.BeginChangeCheck();
                    float tl = Mathf.Max(0f, EditorGUILayout.FloatField(m_TopLeftContent, current.x));
                    float tr = Mathf.Max(0f, EditorGUILayout.FloatField(m_TopRightContent, current.y));
                    float br = Mathf.Max(0f, EditorGUILayout.FloatField(m_BottomRightContent, current.z));
                    float bl = Mathf.Max(0f, EditorGUILayout.FloatField(m_BottomLeftContent, current.w));

                    if (EditorGUI.EndChangeCheck())
                    {
                        m_CornerRadii.vector4Value = new Vector4(tl, tr, br, bl);
                    }
                    EditorGUI.indentLevel--;
                }
            }

            // ── Stroke Section ──
            EditorGUILayout.Space(6);
            EditorGUILayout.LabelField(m_StrokeHeader, EditorStyles.boldLabel);

            if (m_StrokeEnabled != null)
            {
                EditorGUILayout.PropertyField(m_StrokeEnabled, m_StrokeEnabledContent);

                if (m_StrokeEnabled.boolValue)
                {
                    EditorGUI.indentLevel++;

                    if (m_StrokeWidth != null)
                    {
                        EditorGUI.BeginChangeCheck();
                        float width = EditorGUILayout.FloatField(m_StrokeWidthContent, m_StrokeWidth.floatValue);
                        if (EditorGUI.EndChangeCheck())
                        {
                            m_StrokeWidth.floatValue = Mathf.Max(0f, width);
                        }
                    }

                    if (m_StrokeColor != null)
                    {
                        EditorGUILayout.PropertyField(m_StrokeColor, m_StrokeColorContent);
                    }

                    if (m_StrokePosition != null)
                    {
                        EditorGUILayout.PropertyField(m_StrokePosition, m_StrokePositionContent);
                    }

                    if (m_StrokeIgnoreInMask != null)
                    {
                        EditorGUILayout.PropertyField(m_StrokeIgnoreInMask, m_StrokeIgnoreInMaskContent);
                    }

                    EditorGUI.indentLevel--;
                }
            }

            // ── Effects / Drop Shadow Section ──
            EditorGUILayout.Space(6);
            EditorGUILayout.LabelField(m_EffectsHeader, EditorStyles.boldLabel);
            EditorGUILayout.LabelField(m_DropShadowHeader, EditorStyles.miniBoldLabel);

            if (m_ShadowEnabled != null)
            {
                EditorGUILayout.PropertyField(m_ShadowEnabled, m_ShadowEnabledContent);

                if (m_ShadowEnabled.boolValue)
                {
                    EditorGUI.indentLevel++;

                    if (m_ShadowOffsetX != null)
                    {
                        EditorGUILayout.PropertyField(m_ShadowOffsetX, m_ShadowXContent);
                    }

                    if (m_ShadowOffsetY != null)
                    {
                        EditorGUILayout.PropertyField(m_ShadowOffsetY, m_ShadowYContent);
                    }

                    if (m_ShadowBlur != null)
                    {
                        EditorGUI.BeginChangeCheck();
                        float blur = EditorGUILayout.FloatField(m_ShadowBlurContent, m_ShadowBlur.floatValue);
                        if (EditorGUI.EndChangeCheck())
                        {
                            m_ShadowBlur.floatValue = Mathf.Max(0f, blur);
                        }
                    }

                    if (m_ShadowSpread != null)
                    {
                        EditorGUILayout.PropertyField(m_ShadowSpread, m_ShadowSpreadContent);
                    }

                    if (m_ShadowColor != null)
                    {
                        EditorGUILayout.PropertyField(m_ShadowColor, m_ShadowColorContent);
                    }

                    EditorGUI.indentLevel--;
                }
            }

            EditorGUILayout.Space(4);
            EditorGUILayout.LabelField(m_InnerShadowHeader, EditorStyles.miniBoldLabel);

            if (m_InnerShadowEnabled != null)
            {
                EditorGUILayout.PropertyField(m_InnerShadowEnabled, m_InnerShadowEnabledContent);

                if (m_InnerShadowEnabled.boolValue)
                {
                    EditorGUI.indentLevel++;

                    if (m_InnerShadowOffsetX != null)
                    {
                        EditorGUILayout.PropertyField(m_InnerShadowOffsetX, m_InnerShadowXContent);
                    }

                    if (m_InnerShadowOffsetY != null)
                    {
                        EditorGUILayout.PropertyField(m_InnerShadowOffsetY, m_InnerShadowYContent);
                    }

                    if (m_InnerShadowBlur != null)
                    {
                        EditorGUI.BeginChangeCheck();
                        float blur = EditorGUILayout.FloatField(m_InnerShadowBlurContent, m_InnerShadowBlur.floatValue);
                        if (EditorGUI.EndChangeCheck())
                        {
                            m_InnerShadowBlur.floatValue = Mathf.Max(0f, blur);
                        }
                    }

                    if (m_InnerShadowSpread != null)
                    {
                        EditorGUILayout.PropertyField(m_InnerShadowSpread, m_InnerShadowSpreadContent);
                    }

                    if (m_InnerShadowColor != null)
                    {
                        EditorGUILayout.PropertyField(m_InnerShadowColor, m_InnerShadowColorContent);
                    }

                    EditorGUI.indentLevel--;
                }
            }

            // ── Raycast Section ──
            if (m_UseRoundedRaycast != null)
            {
                EditorGUILayout.Space(4);
                EditorGUILayout.PropertyField(m_UseRoundedRaycast, m_RaycastContent);
            }

            if (serializedObject.ApplyModifiedProperties())
            {
                foreach (var targetObj in targets)
                {
                    if (targetObj is FigmaImage figmaImage)
                    {
                        figmaImage.SetVerticesDirty();
                    }
                }
            }
        }

        [MenuItem("GameObject/UI/Figma Image", false, 2001)]
        public static void CreateFigmaImage(MenuCommand menuCommand)
        {
            GameObject go = new GameObject("Figma Image", typeof(RectTransform), typeof(CanvasRenderer), typeof(FigmaImage));

            GameObject parent = menuCommand.context as GameObject;
            if (parent == null || parent.GetComponentInParent<Canvas>() == null)
            {
                Canvas canvas = Object.FindAnyObjectByType<Canvas>();
                if (canvas == null)
                {
                    GameObject canvasGo = new GameObject("Canvas", typeof(RectTransform), typeof(Canvas), typeof(CanvasScaler), typeof(GraphicRaycaster));
                    canvas = canvasGo.GetComponent<Canvas>();
                    canvas.renderMode = RenderMode.ScreenSpaceOverlay;
                    canvasGo.layer = LayerMask.NameToLayer("UI");

                    if (Object.FindAnyObjectByType<UnityEngine.EventSystems.EventSystem>() == null)
                    {
                        new GameObject("EventSystem", typeof(UnityEngine.EventSystems.EventSystem), typeof(UnityEngine.EventSystems.StandaloneInputModule));
                    }
                }
                parent = canvas.gameObject;
            }

            GameObjectUtility.SetParentAndAlign(go, parent);
            go.layer = LayerMask.NameToLayer("UI");

            RectTransform rect = go.GetComponent<RectTransform>();
            rect.sizeDelta = new Vector2(200f, 80f);
            rect.anchoredPosition = Vector2.zero;

            FigmaImage img = go.GetComponent<FigmaImage>();
            img.color = Color.white;
            img.SetRadius(16f);

            Undo.RegisterCreatedObjectUndo(go, "Create Figma Image");
            Selection.activeGameObject = go;
        }

        [MenuItem("CONTEXT/RoundedImage/Upgrade to FigmaImage", false)]
        public static void UpgradeRoundedImageToFigmaImage(MenuCommand command)
        {
            RoundedImage oldComponent = command.context as RoundedImage;
            if (oldComponent == null) return;

            GameObject go = oldComponent.gameObject;
            Undo.RecordObject(go, "Upgrade RoundedImage to FigmaImage");

            // Extract existing properties
            bool link = oldComponent.LinkCorners;
            float radius = oldComponent.Radius;
            Vector4 radii = oldComponent.CornerRadii;
            bool raycast = oldComponent.UseRoundedRaycast;
            Color col = oldComponent.color;
            Sprite spr = oldComponent.sprite;
            Material mat = oldComponent.material;
            bool raycastTarget = oldComponent.raycastTarget;
            Image.Type imgType = oldComponent.type;

            // Remove legacy component and add FigmaImage
            Undo.DestroyObjectImmediate(oldComponent);
            FigmaImage newComponent = Undo.AddComponent<FigmaImage>(go);

            newComponent.color = col;
            newComponent.sprite = spr;
            newComponent.material = mat;
            newComponent.raycastTarget = raycastTarget;
            newComponent.type = imgType;
            newComponent.UseRoundedRaycast = raycast;

            if (link)
            {
                newComponent.SetRadius(radius);
            }
            else
            {
                newComponent.SetCornerRadii(radii);
            }

            EditorUtility.SetDirty(go);
            Debug.Log($"[FigmaImage] Successfully upgraded '{go.name}' from RoundedImage to FigmaImage.", go);
        }
    }
}
